---
- name: Install Nginx
  sudo: yes
  apt: pkg=nginx state=latest

- name: Create web root
  shell: mkdir -p {{ web_root }}

- name: Change default nginx site
  sudo: yes
  template: src={{ nginx.vhost_template }} dest={{ nginx.vhost_file }}
  notify: restart nginx
